import type { Cliente, Clase, Reserva, Usuario } from "./types"

// Datos dummy para clientes
export const clientes: Cliente[] = [
  {
    id_cliente: "1",
    email: "maria.garcia@email.com",
    nombre: "María García",
    telefono: "+34 600 123 456",
    fecha_registro: "2023-01-15",
  },
  {
    id_cliente: "2",
    email: "juan.lopez@email.com",
    nombre: "Juan López",
    telefono: "+34 600 234 567",
    fecha_registro: "2023-02-20",
  },
  {
    id_cliente: "3",
    email: "ana.martinez@email.com",
    nombre: "Ana Martínez",
    telefono: "+34 600 345 678",
    fecha_registro: "2023-03-10",
  },
  {
    id_cliente: "4",
    email: "carlos.rodriguez@email.com",
    nombre: "Carlos Rodríguez",
    telefono: "+34 600 456 789",
    fecha_registro: "2023-04-05",
  },
  {
    id_cliente: "5",
    email: "lucia.fernandez@email.com",
    nombre: "Lucía Fernández",
    telefono: "+34 600 567 890",
    fecha_registro: "2023-05-12",
  },
  {
    id_cliente: "6",
    email: "pedro.gonzalez@email.com",
    nombre: "Pedro González",
    telefono: "+34 600 678 901",
    fecha_registro: "2023-06-18",
  },
  {
    id_cliente: "7",
    email: "isabel.moreno@email.com",
    nombre: "Isabel Moreno",
    telefono: "+34 600 789 012",
    fecha_registro: "2023-07-25",
  },
  {
    id_cliente: "8",
    email: "roberto.silva@email.com",
    nombre: "Roberto Silva",
    telefono: "+34 600 890 123",
    fecha_registro: "2023-08-30",
  },
]

// Datos dummy para instructores
export const instructores = [
  {
    id_instructor: "1",
    nombre: "Pedro Sánchez",
    email: "pedro.sanchez@siclo.com",
    especialidades: ["Siclo", "Yoga"],
    experiencia: "5 años",
    certificaciones: ["RYT-200", "Spinning Certified"],
    telefono: "+34 611 111 111",
    fecha_contratacion: "2019-03-15",
  },
  {
    id_instructor: "2",
    nombre: "Carmen López",
    email: "carmen.lopez@siclo.com",
    especialidades: ["Yoga", "Barre"],
    experiencia: "7 años",
    certificaciones: ["RYT-500", "Barre Above Certified"],
    telefono: "+34 622 222 222",
    fecha_contratacion: "2017-08-20",
  },
  {
    id_instructor: "3",
    nombre: "Miguel Torres",
    email: "miguel.torres@siclo.com",
    especialidades: ["Siclo", "Ejercito"],
    experiencia: "4 años",
    certificaciones: ["HIIT Certified", "Spinning Master"],
    telefono: "+34 633 333 333",
    fecha_contratacion: "2020-01-10",
  },
  {
    id_instructor: "4",
    nombre: "Laura Ruiz",
    email: "laura.ruiz@siclo.com",
    especialidades: ["Barre", "Yoga"],
    experiencia: "6 años",
    certificaciones: ["Pilates Mat", "Barre Intensity"],
    telefono: "+34 644 444 444",
    fecha_contratacion: "2018-05-12",
  },
  {
    id_instructor: "5",
    nombre: "David Moreno",
    email: "david.moreno@siclo.com",
    especialidades: ["Ejercito", "Siclo"],
    experiencia: "3 años",
    certificaciones: ["CrossFit Level 1", "Functional Training"],
    telefono: "+34 655 555 555",
    fecha_contratacion: "2021-09-01",
  },
  {
    id_instructor: "6",
    nombre: "Sofia Vega",
    email: "sofia.vega@siclo.com",
    especialidades: ["Yoga", "Barre"],
    experiencia: "8 años",
    certificaciones: ["RYT-500", "Yin Yoga Certified"],
    telefono: "+34 666 666 666",
    fecha_contratacion: "2016-02-28",
  },
]

// Datos dummy para clases
export const clases: Clase[] = [
  {
    id_clase: "1",
    pais: "España",
    ciudad: "Madrid",
    disciplina: "Siclo",
    estudio: "Síclo Chamberí",
    salon: "Sala 1",
    instructor: "Pedro Sánchez",
    dia: "Lunes",
    hora: "09:00",
    cupos_totales: 20,
  },
  {
    id_clase: "2",
    pais: "España",
    ciudad: "Madrid",
    disciplina: "Yoga",
    estudio: "Síclo Chamberí",
    salon: "Sala 2",
    instructor: "Carmen López",
    dia: "Lunes",
    hora: "10:30",
    cupos_totales: 15,
  },
  {
    id_clase: "3",
    pais: "España",
    ciudad: "Barcelona",
    disciplina: "Barre",
    estudio: "Síclo Eixample",
    salon: "Sala 1",
    instructor: "Laura Ruiz",
    dia: "Martes",
    hora: "18:00",
    cupos_totales: 12,
  },
  {
    id_clase: "4",
    pais: "España",
    ciudad: "Madrid",
    disciplina: "Ejercito",
    estudio: "Síclo Chamberí",
    salon: "Sala 3",
    instructor: "Miguel Torres",
    dia: "Miércoles",
    hora: "19:30",
    cupos_totales: 18,
  },
  {
    id_clase: "5",
    pais: "España",
    ciudad: "Barcelona",
    disciplina: "Yoga",
    estudio: "Síclo Eixample",
    salon: "Sala 2",
    instructor: "Sofia Vega",
    dia: "Jueves",
    hora: "08:00",
    cupos_totales: 16,
  },
  {
    id_clase: "6",
    pais: "España",
    ciudad: "Madrid",
    disciplina: "Siclo",
    estudio: "Síclo Malasaña",
    salon: "Sala 1",
    instructor: "David Moreno",
    dia: "Viernes",
    hora: "07:00",
    cupos_totales: 22,
  },
]

// Datos dummy para reservas
export const reservas: Reserva[] = [
  {
    id_reserva: "1",
    id_clase: "1",
    id_cliente: "1",
    creador_pedido: "cliente",
    metodo_pago: "tarjeta",
    estatus: "confirmada",
    fecha_reserva: "2024-01-10",
    fecha_clase: "2024-01-15",
  },
  {
    id_reserva: "2",
    id_clase: "1",
    id_cliente: "2",
    creador_pedido: "cliente",
    metodo_pago: "efectivo",
    estatus: "confirmada",
    fecha_reserva: "2024-01-11",
    fecha_clase: "2024-01-15",
  },
  {
    id_reserva: "3",
    id_clase: "2",
    id_cliente: "1",
    creador_pedido: "admin",
    metodo_pago: "tarjeta",
    estatus: "confirmada",
    fecha_reserva: "2024-01-12",
    fecha_clase: "2024-01-15",
  },
  {
    id_reserva: "4",
    id_clase: "3",
    id_cliente: "3",
    creador_pedido: "cliente",
    metodo_pago: "tarjeta",
    estatus: "confirmada",
    fecha_reserva: "2024-01-13",
    fecha_clase: "2024-01-16",
  },
  {
    id_reserva: "5",
    id_clase: "4",
    id_cliente: "4",
    creador_pedido: "cliente",
    metodo_pago: "transferencia",
    estatus: "pendiente",
    fecha_reserva: "2024-01-14",
    fecha_clase: "2024-01-17",
  },
  {
    id_reserva: "6",
    id_clase: "1",
    id_cliente: "1",
    creador_pedido: "cliente",
    metodo_pago: "tarjeta",
    estatus: "confirmada",
    fecha_reserva: "2024-01-20",
    fecha_clase: "2024-01-22",
  },
  {
    id_reserva: "7",
    id_clase: "2",
    id_cliente: "5",
    creador_pedido: "cliente",
    metodo_pago: "tarjeta",
    estatus: "confirmada",
    fecha_reserva: "2024-01-21",
    fecha_clase: "2024-01-22",
  },
  {
    id_reserva: "8",
    id_clase: "3",
    id_cliente: "6",
    creador_pedido: "cliente",
    metodo_pago: "efectivo",
    estatus: "confirmada",
    fecha_reserva: "2024-01-22",
    fecha_clase: "2024-01-23",
  },
]

// Datos dummy para usuarios del sistema
export const usuarios: Usuario[] = [
  {
    id_usuario: "1",
    nombre: "Admin Principal",
    email: "admin@siclo.com",
    rol: "admin",
    fecha_creacion: "2023-01-01",
  },
  {
    id_usuario: "2",
    nombre: "Operador Madrid",
    email: "operador.madrid@siclo.com",
    rol: "operador",
    fecha_creacion: "2023-02-15",
  },
  {
    id_usuario: "3",
    nombre: "Operador Barcelona",
    email: "operador.barcelona@siclo.com",
    rol: "operador",
    fecha_creacion: "2023-03-01",
  },
]
